### ISSUE TITLE
Artikelcontainer wird immer mit ausgegeben

### ISSUE THREAD

**Issue by frontendschlampe** [hofff/contao-content#1]
In Contao 4 wird bei der Benutzung des CE "Inhaltsreferenzen" der Artikelcontainer immer mit ausgegeben, obwohl die Option "Artikelcontainer ausgeben" deaktiviert ist

**Comment by backbone87** [comment]
Es gibt hier zwei verschiedene Optionen. Eine für alle Referenzen und eine pro Referenz

**Comment by frontendschlampe** [comment]
Ich bin hier bei der Option für die jeweilige einzelne Referenz.

**Comment by frontendschlampe** [comment]
des weiteren gibt es beim CE nur diese eine Option "Artikelcontainer ausgeben"

**Comment by backbone87** [comment]
custom template problem
