### ISSUE TITLE
Problem mit doctrine/dbal 3.4.0

### ISSUE THREAD

**Issue by frontendschlampe** [hofff/contao-content#10]
Nach einem Update auf `doctrine/dbal 3.4.0` soll im Installtool die Tabelle bzw. View gelöscht werden:

`DROP TABLE hofff_content_tree`

Mit `doctrine/dbal 3.3.8` tritt das Problem nicht auf.

- PHP 8.1
- Contao 4.13.6

**Comment by dmolineus** [comment]
See https://github.com/doctrine/dbal/issues/5579

**Comment by dmolineus** [comment]
Doctrine bekommt einen Fix, ich habe ein Konflikt mit doctrine/dbal 3.4.0 hinzugefügt.
