### ISSUE TITLE
Problem in C4.4 when using Frontend preview with show hidden elements

### ISSUE THREAD

**Issue by discordier** [hofff/contao-content#3]
I have the Problem that I get an exception that `false` gets passed to `StringUtil::prefixEach` instead of array.

The source of the problem is, that in [src/DCA/DCABuilder.php#L96](https://github.com/hofff/contao-content/blob/2.x/src/DCA/DCABuilder.php#L96) the test is for `$user->isAdmin`.
However, the `BackendUser` instance is not authenticated in this code location and therefor the test fails.
I fixed it by changing
```diff
 		if(BE_USER_LOGGED_IN) {
 			$user = BackendUser::getInstance();
+			$user->authenticate();
 			$user->isAdmin || $factory->getConfig()->setRoots(StringUtil::prefixEach($user->pagemounts, 'page.'));
```

**Comment by backbone87** [comment]
this should already be fixed in the latest version: https://github.com/hofff/contao-content/blob/2.x/src/DCA/DCABuilder.php#L97

**Comment by discordier** [comment]
Are you sure that works?
I mean, IMO you are now checking against an unauthenticated BE user which has `null` in `isAdmin` and `pagemounts` and therefore the condition becomes equivalent of `if (false) {`...

**Comment by backbone87** [comment]
I was Pretty sure i checked the default value to be false, eben for anon users
