### ISSUE TITLE
Problem im Zusammenspiel mit RockSolid Frontend Helper

### ISSUE THREAD

**Issue by frontendschlampe** [hofff/contao-content#5]
Wenn RockSolid Frontend Helper aktiviert, dann werden die verknüpften Artikel nicht ausgegeben. Sobald ich es deaktiviere funktioniert es ohne Probleme.

**Comment by dmolineus** [comment]
Ich kann das lokal bei mir nicht nachstellen. Funktioniert mit und ohne Frontend Helper. Wie ist denn genau das Setup? Ist es ggf. ein CSS Problem?

**Comment by dmolineus** [comment]
Ich stufe dies als Fehler des Frontendhelpers ein, siehe https://github.com/madeyourday/contao-rocksolid-frontend-helper/issues/37

**Comment by frontendschlampe** [comment]
sollte gelöst sein
